# River Horizon - core/constants.py

# Flight Modes
MODE_MANUAL = "MANUAL"
MODE_STABILIZE = "STABILIZE"
MODE_GUIDED = "GUIDED"
MODE_AUTO = "AUTO"
MODE_RTH = "RTL"
MODE_LAND = "LAND"

# Safety Statuses
STATUS_OK = "OK"
STATUS_WARNING = "WARNING"
STATUS_CRITICAL = "CRITICAL"
STATUS_FAILSAFE = "FAILSAFE"

# Connectivity
HB_INTERVAL_S = 1.0
TELEMETRY_RATE_HZ = 10

# Geofence
GEOFENCE_TYPE_CYLINDER = "CYLINDER"
GEOFENCE_ACTION_RTL = "RTL"
GEOFENCE_ACTION_LOITER = "LOITER"
